"""Comments fix

Revision ID: 1d7cacb4a0e9
Revises: cfbfd59d93e3
Create Date: 2019-03-14 01:44:20.555097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7cacb4a0e9'
down_revision = 'cfbfd59d93e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_text', sa.Text(), nullable=False))
    op.drop_column('comments', 'commet_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commet_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'comment_text')
    # ### end Alembic commands ###
