"""Story fix

Revision ID: 3eca5e516ad0
Revises: 1d7cacb4a0e9
Create Date: 2019-03-14 02:06:57.485405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eca5e516ad0'
down_revision = '1d7cacb4a0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('storys_title_key', 'storys', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('storys_title_key', 'storys', ['title'])
    # ### end Alembic commands ###
